[build]
  command = "npm run build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- . ':!.netlify' ':!*.md'"

[build.environment]
  NODE_VERSION = "18.20.4"
  NETLIFY_SKIP_SECRETS_SCANNING = "true"
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_OMIT_PATHS = ".netlify/**,.next/**,node_modules/**"
  CI = "true"

# Next.js plugin for proper API routes handling
[[plugins]]
  package = "@netlify/plugin-nextjs"

# API routes should not be redirected
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

# All other routes go to Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"